### ISSUE TITLE
Show not enough entries page when needed

### ISSUE THREAD

**Issue by elijahkim** [elijahkim/looseleaf#25]
The analysis doesn't really work when there aren't enough entries. We should convey this to the user so the user isn't confused

**Comment by sherry33** [comment]
![screen shot 2016-10-15 at 3 34 41 pm](https://cloud.githubusercontent.com/assets/22825674/19410815/0767f196-92ed-11e6-91ea-e3101fed28e8.png)

**Comment by sherry33** [comment]
![sad loose leaf man](https://cloud.githubusercontent.com/assets/22825674/19410818/0d844dae-92ed-11e6-91d9-86ae160f246a.png)
